---
title: "EDLD 652 Midterm"
author: "Chen Su"
format: 
  html:
    embed-resources: true
execute: 
  warning: false
---


```{r}
#| label: part-a-data-1

library(tidyverse)
library(rio)
library(glue)
library(here)

download_file <- function(year) {
  link <- glue::glue("https://www.oregon.gov/ode/educator-resources/assessment/TestResults20{year}/pagr_schools_ela_raceethnicity_{year-1}{year}.xlsx")
  rio::import(link, setclass = "tibble", na = c("-", "--", "*"))
}

df <- bind_rows(lapply(15:18, download_file))

df

# data cleaning

library(janitor)

df_1 <- df |>
  clean_names() |>
  filter(student_group == "White" | student_group == "Hispanic/Latino") |>
  select(1, 3, 5, 7, 8, 11, 13, 15, 17) |>
  pivot_longer(
    cols = c(number_level_1, number_level_2, number_level_3, number_level_4),
    names_to = "level",
    names_prefix = "number_level_",
    values_to = "n",
    values_drop_na = TRUE
  ) 

df_1

```


```{r}
#| label: part-a-data-2

df_2 <- df_1 |>
  group_by(academic_year, district, student_group, level) |>
  summarize(n = sum(n, na.rm = TRUE),
    .groups = "drop") |>
  pivot_wider(
    names_from = student_group,
    values_from = n
  ) |> 
  drop_na()
  
n_schools <- df_1 |>
  group_by(district) |>
  summarize(n_schools = n_distinct(school),
            .groups = "drop")

df_2 <- df_2 |>
  left_join(n_schools, by = "district")

# clean variable name and reorder

df_2 <- df_2 |>
  relocate(n_schools, .before = level) |>
  rename(hispanic_latino = `Hispanic/Latino`,
         white = White) |>
  arrange(district)

df_2

```


```{r}
#| label: part-b-achievement-set-up

library(remotes)

remotes::install_github("datalorax/gapr")

library(gapr)
df_2[1:4, ] |> # data source - just first four rows for first district
  estimate_v("white", "hispanic_latino") # columns for reference/focal groups

```


```{r}
#| label: part-b-achievement-1

library(purrr)

v_map <- df_2 |>
  group_by(academic_year, district) |>
  nest() |>
  mutate(
    v = map(data, ~estimate_v(.x, "white", "hispanic_latino"))
  ) |>
  unnest(v) 


v_sum <- df_2 |>
  nest_by(academic_year, district) |>
  summarize(
    estimate_v(data, "white", "hispanic_latino"),
    .groups = "drop"
  )


```


```{r}
#| label: part-b-achievement-2

v_map_p <- v_map |>
  select(-data, -auc, -v_se) |>
  rename(v_map = v) 

v_sum_p <- v_sum |>
  rename(v_sum = v) |>
    select(-auc, -v_se)

v_compare <- v_map_p |>
  left_join(v_sum_p, by = join_by(academic_year, district))

# plotting

ggplot(v_compare, aes(x = v_sum, y = v_map)) +
  geom_point(color = "gray", alpha = 5) +
  geom_abline(slope = 1, intercept = 0, color = "lightblue", linewidth = 1.2) +
  labs(
    x = "V (`nest_by() |> summarize()`)",
    y = "V (`group_by() |> nest() |> mutate() |> map()`)"
  ) +
  theme_minimal(base_size = 14)

```


```{r}
#| label: part-b-achievement-3

dists <- unique(v_map$district)[1:100]

v_plot <- v_map |> 
  mutate(n = map_int(data, ~unique(.x$n_schools))) |>
  select(-data) |> 
  filter(district %in% dists)

# method 1
by_district <- v_plot |>
  group_by(district, n) |>
  nest()

plots_1 <- by_district |>
  mutate(
    plots = pmap(list(data, district, n), 
                 ~ggplot(..1, aes(x = academic_year, y = v, group = 1)) + 
                 geom_hline(yintercept = 0, color = "red", linewidth = 0.6) + 
                 geom_line(color = "lightgray", size = 0.6) + 
                 geom_point(color = "skyblue", size = 4) + 
                 geom_errorbar(aes(ymin = v - v_se, ymax = v + v_se), color = "darkgray", 
                               linewidth = 1, width = 0.3) + 
                 labs( title = glue("Achievement Gap Estimates: {..2}"),
                       subtitle = "Negative values indicate White students have higher average achievement\nPositive values indicate Hispanic/Latino students have higher average achievement",
                       x = "School year", 
                       y = "Average achievement difference (SD units)",
      caption = glue("Note: District included {..3} schools.")
    ) + theme_minimal(base_size = 14))
  )

plots_1$plots[[1]]

# method 2
plots_2 <- v_plot |>
  ungroup() |>
  nest_by (district, n) |>
  mutate(plots = list(
    ggplot(data, aes(x = academic_year, y = v, group = 1)) + 
                 geom_hline(yintercept = 0, color = "red", linewidth = 0.6) + 
                 geom_line(color = "lightgray", size = 0.6) + 
                 geom_point(color = "skyblue", size = 4) + 
                 geom_errorbar(aes(ymin = v - v_se, ymax = v + v_se), color = "darkgray", 
                               linewidth = 1, width = 0.3) + 
                 labs( title = glue("Achievement Gap Estimates: {district}"),
                       subtitle = "Negative values indicate White students have higher average achievement\nPositive values indicate Hispanic/Latino students have higher average achievement",
                       x = "School year", 
                       y = "Average achievement difference (SD units)",
      caption = glue("Note: District included: ", n, " schools.")
    ) + theme_minimal(base_size = 14))
  )

plots_2$plots[[1]]

```


```{r}
#| label: part-b-achievement-4

fs::dir_create(here::here("plots", "achievement"))

files <- str_replace_all(
  tolower(plots_1$district),
  " ",
  "-"
)
paths <- here::here("plots", "achievement", glue("{files}.png"))
paths

plots_1 |> 
  ungroup() |> 
  mutate(path = paths) |> 
  select(plots, path)

plots_1 |> 
  ungroup() |> 
  mutate(path = paths) |> 
  rowwise() |> 
  summarize(
    ggsave(path, plots, 
      width = 9.5, 
      height = 6.5,
      dpi = 500
    )
  )

```

